### PR TITLE
Turn into installable package & add console_script webtoon-downloader

### PR DESCRIPTION
**Pull request by olaf-mandel**
Declare a console_script to be installed that executes the main function. This allows a user to just install this module and then execute the functionality from their path without having to specify the interpreter or the module-name every time.

### CODE REVIEW

**Review by Zehina — APPROVED** [review]
Thanks, this looks great ! 
setup.py is pretty old now, so I probably think I will migrate to using https://github.com/python-poetry/poetry instead and provide wheel files in the releases

**Comment by olaf-mandel** [comment]
> setup.py is pretty old now, so I probably think I will migrate to using https://github.com/python-poetry/poetry instead and provide wheel files in the releases

Did add a commit now that transitions to the `pyproject.toml` syntax. But I used setuptools as a build-tools instead of proetry because it had a nicely documented transition-path for the non-standard directory layout.

**Comment by Zehina** [comment]
> > setup.py is pretty old now, so I probably think I will migrate to using https://github.com/python-poetry/poetry instead and provide wheel files in the releases
> 
> Did add a commit now that transitions to the `pyproject.toml` syntax. But I used setuptools as a build-tools instead of proetry because it had a nicely documented transition-path for the non-standard directory layout.

Thanks for adding it, it looks good. Yeah this initially started as a small script and just keep getting bigger and bigger without ever considering proper directory layout, separate files, etc...
This should do for now though. In the future, it will probably be best to just transition into installing it either from the source or the build from a wheel file (using poetry) and then call the CLI entrypoint rather than using `python webtoon_downloader.py...`

**Comment by Zehina** [comment]
@olaf-mandel might have messed up something for you but everything is merged now. Thank you again

**Pull request merged**
